# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a12b6bdbc36c8945976c8b78bc62f6f50ec41e8e88bb9be5c89cebbcc90a2939ca2627e7dd492795d24d446c4d131d85e4ee5041d81347d6a9d7d159da5a99e4

test:
  secret_key_base: a1735239f9445073c3a1b03411f75d7bdbb66ebb94f9091237670a7c835e4bd9b1027b88f1f25a922c74dda81fbe101f51d72d3116b2308f6c7ec9dce7acfd01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
